### ISSUE TITLE
No rows added when performing indexing

### ISSUE THREAD

**Issue by pshe94** [trilbymedia/grav-plugin-tntsearch#25] opened 2018-02-11 00:58 UTC
After latest update indexing doesn't work at all - it doesn't find any pages. Tested with my own website and completely clean Grav installation (both stable and updated to 1.4.0 RC1), and starting indexing from admin panel and terminal.

Here is terminal output:
```
$ bin/plugin tntsearch index

Re-indexing Search

Total rows 0
Done.
```

After digging around I've found that database exists (and is being created when deleted and performing indexing again), but always is empty.
I'm using Windows 10 (up-to-date) and XAMPP for my web server (PHP version 7.2.1, but it didn't work with 7.2.0 too). All necessary extensions are enabled (PDO Drivers for SQLite and MySQL, PDO and SQLite3 in my php.ini file). But I'm not sure if that even matters, because previous version worked.

**Comment by pshe94** [comment] 2018-02-11 16:42
OK, I have found the culprit. Turns out, Search Filter field in plugin configuration page is not being saved properly.

Config file `user/config/plugins/tntsearch.yaml`
After saving in admin panel (doesn't work):
```
filter:
  items: 'taxonomy@: { category: [news] }'
```

Fixing manually (works):
```
filter:
  items: 
    'taxonomy@': 
        category: [news]
```

Also, is there any way to index every page? Because from what I can see in source code, setting Index Every Page field to Enabled is taken into account AFTER pages are filtered with Search Filter. I've tried using: 
```
filter:
  items: `@none`
```
Unfortunately, it didn't work. I think it would be a good idea to maybe just leave Search Filter empty if someone wants to index all pages.

P.S. In Configuration section in your README.md file, path to the default config file and to the user modifiable one has `-` in it's name, but it's wrong (`user/plugins/tnt-search/tnt-search.yaml` should be `user/plugins/tntsearch/tntsearch.yaml`, and `user/config/plugins/tnt-search.yaml` should be `user/config/plugins/tntsearch.yaml`) 🙂

**Comment by Hestat** [comment] 2018-02-11 23:29
I can confirm this same issue, and the fix presented above also works for me. TY pshe94

**Comment by pshe94** [comment] 2018-02-12 02:27
After digging around I've found out that Grav can't parse so 'advanced' YAML syntax, if it is being stored as string. `Evaluate` function in `Grav\Common\Page\Page.php` can only handle dot notations (for example `@self.modular`), but not list of key/values within curly braces.

Right now I wrote a simple and rather dirty fix, that parses YAML stored in string to an array inside of `query` function in `plugins\tntsearch\classes\GravConnector.php` file, using Symfony YAML parser. 
For anyone interested:
```
...
use Symfony\Component\Yaml\Parser;
...
public function query($query) {
    ...
    $gtnt = new GravTNTSearch();

    //dirty fix for not parsing YAML properly
    if(is_string($filter['items'])) {
        $yaml = new Parser();
        $filter['items'] = $yaml->parse($filter['items']);
    }
    ...
}
```
This works, but I don't think it should be considered as a proper fix.

**Comment by dgaussin** [comment] 2018-02-12 10:55
@pshe94 I used '@root.descendants' as filter to index every page. Seems worked.

**Comment by rhukster** [comment] 2018-02-15 02:47
I just ran into this also and fixed it before i found @pshe94 's comment.. my fix was similar:

```
        if ($filter && array_key_exists('items', $filter)) {

            if (is_string($filter['items'])) {
                $filter['items'] = Yaml::parse($filter['items']);
            }
        ...
```

However, I think the proper fix is in the YAML option for the textarea field and i'll investigate this, but in the meantime the fix should work.

**Comment by ArsMediaBrasil** [comment] 2018-03-09 15:37
I've tried these all and upgraded to the v1.2.5, and this is still not indexing the pages.
I'm running the "Mediator" theme. Any clues? Thanks

**Comment by cpfeifer** [comment] 2018-03-22 02:14
I'm having the same issue. I fixed it by removing the filter code in the plugins/tntsearch/tntsearch.yaml

Whatever is happening, it's not seeing the override file in config/plugins/tntsearch.yaml, so any changes there have no effect for me. Tested on a few different installs, dev server, live server and local server, same thing on all of them

Looks like you guys know why this happening, but this is a super quick easy fix. It might not survive an update but hopefully an update means it's been fixed altogether :)

**Comment by cpfeifer** [comment] 2018-03-22 02:45
Actually never mind on the overrides, that is working. But removing the filter code yaml file is a quick fix that worked for me. 

I thought there was an issue with the override because I was changing the "powered by" value in the file, and I wasn't seeing it change on the front end. I looked in the partials/twig file and there's no conditional to control it so it's always on no matter what the value is. I'll start a different thread for that.

**Closed** 2018-10-28 23:11 UTC
Labels: Fixed
